app_path:
  - C:/Users/yc-pc/Desktop/PLCTest.exe.lnk
  - C:/Users/yc-pc/Desktop/main.exe.lnk
  - C:/Users/yc-pc/Desktop/el-jk-us.exe.lnk

kill_app:
  - PLCTest.exe
  - main.exe
  - el-jk-us.exe

clear_cache_path:
  - C:/Users/yc-pc/Desktop/dobby/gui_jkus-0.1.4/gui_jkus-0.1.4/resources/app/src/cache
  - C:/Users/yc-pc/Desktop/dobby/el_panel-jkf5-0.4.0/temp_pic

copy:
  -
    - /home/ubuntu/Pictures/3.jpg
    - /home/ubuntu/Pictures/C

maximize_app: YC GUI

mouse_click:
  -
    - 200  # x
    - 400  # y
    - 3

url_config:
  plc_url: localhost:9111/plc
  plc_station: 2
  el_position: D399
  revolving_table_position: D399
